// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzLQlv5WkQLt9bD6AfsVzx6_htTy76VgA',
    appId: '1:736501587460:web:fe486392cea3fde09fdf51',
    messagingSenderId: '736501587460',
    projectId: 'worky-9c29e',
    authDomain: 'worky-9c29e.firebaseapp.com',
    storageBucket: 'worky-9c29e.appspot.com',
    databaseURL: 'https://worky-9c29e-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBISUpI778esxAl_92OBhMU4k0MLNvSl8M',
    appId: '1:736501587460:android:71e0ee5903eb8d7b9fdf51',
    messagingSenderId: '736501587460',
    projectId: 'worky-9c29e',
    storageBucket: 'worky-9c29e.appspot.com',
    databaseURL: 'https://worky-9c29e-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMBZliCC4jPnl9SV5jqxBLFZF7-fUzbeo',
    appId: '1:736501587460:ios:cc62422ef5fabd2c9fdf51',
    messagingSenderId: '736501587460',
    projectId: 'worky-9c29e',
    storageBucket: 'worky-9c29e.appspot.com',
    iosBundleId: 'com.example.workout',
    databaseURL: 'https://worky-9c29e-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMBZliCC4jPnl9SV5jqxBLFZF7-fUzbeo',
    appId: '1:736501587460:ios:cc62422ef5fabd2c9fdf51',
    messagingSenderId: '736501587460',
    projectId: 'worky-9c29e',
    storageBucket: 'worky-9c29e.firebasestorage.app',
    iosBundleId: 'com.example.workout',
    databaseURL: 'https://worky-9c29e-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzLQlv5WkQLt9bD6AfsVzx6_htTy76VgA',
    appId: '1:736501587460:web:eb322335dad900a69fdf51',
    messagingSenderId: '736501587460',
    projectId: 'worky-9c29e',
    authDomain: 'worky-9c29e.firebaseapp.com',
    storageBucket: 'worky-9c29e.firebasestorage.app',
    databaseURL: 'https://worky-9c29e-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );
}